"""train_station_timetable

Revision ID: 18c46199bc66
Revises: 49c1827789d1
Create Date: 2026-03-27 14:41:03.875361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c46199bc66'
down_revision: Union[str, None] = '49c1827789d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Integer(), nullable=True),
    sa.Column('is_major', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_master_station_code'), 'station_master', ['station_code'], unique=True)
    op.create_table('train_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('runs_on', sa.String(length=50), nullable=True),
    sa.Column('total_distance_km', sa.Integer(), nullable=True),
    sa.Column('origin_code', sa.String(length=10), nullable=True),
    sa.Column('destination_code', sa.String(length=10), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_train_master_name', 'train_master', ['name'], unique=False)
    op.create_index(op.f('ix_train_master_train_no'), 'train_master', ['train_no'], unique=True)
    op.create_table('trip_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.UUID(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(length=8), nullable=True),
    sa.Column('departure_time', sa.String(length=8), nullable=True),
    sa.Column('halt_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distance_km', sa.Integer(), server_default='0', nullable=False),
    sa.Column('day', sa.Integer(), server_default='1', nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['station_code'], ['station_master.station_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['train_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'sequence', name='uq_trip_schedule_train_seq')
    )
    op.create_index('ix_trip_schedule_station_code', 'trip_schedule', ['station_code'], unique=False)
    op.create_index('ix_trip_schedule_train_id', 'trip_schedule', ['train_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_schedule_train_id', table_name='trip_schedule')
    op.drop_index('ix_trip_schedule_station_code', table_name='trip_schedule')
    op.drop_table('trip_schedule')
    op.drop_index(op.f('ix_train_master_train_no'), table_name='train_master')
    op.drop_index('ix_train_master_name', table_name='train_master')
    op.drop_table('train_master')
    op.drop_index(op.f('ix_station_master_station_code'), table_name='station_master')
    op.drop_table('station_master')
    # ### end Alembic commands ###
