"""add_gamification_tables

Revision ID: 8c1ad03bb8fb
Revises: c5e4645d33bf
Create Date: 2026-03-27 15:20:29.483250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1ad03bb8fb'
down_revision: Union[str, None] = 'c5e4645d33bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('karma_bonus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karma_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karma_events_created_at'), 'karma_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_karma_events_user_id'), 'karma_events', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('streak_type', sa.String(length=30), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('best_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'streak_type', name='uq_streak')
    )
    op.create_index('ix_streak_user', 'streaks', ['user_id'], unique=False)
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index('ix_user_badge_user', 'user_badges', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index('ix_user_badge_user', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_index('ix_streak_user', table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_karma_events_user_id'), table_name='karma_events')
    op.drop_index(op.f('ix_karma_events_created_at'), table_name='karma_events')
    op.drop_table('karma_events')
    op.drop_table('badges')
    # ### end Alembic commands ###
