"""add_tracking_tables

Revision ID: c5e4645d33bf
Revises: ca77d3939fec
Create Date: 2026-03-27 15:11:59.759025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e4645d33bf'
down_revision: Union[str, None] = 'ca77d3939fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_positions',
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('from_station_code', sa.String(length=10), nullable=True),
    sa.Column('to_station_code', sa.String(length=10), nullable=True),
    sa.Column('next_station_code', sa.String(length=10), nullable=True),
    sa.Column('next_station_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_known_station_code', sa.String(length=10), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('train_no')
    )
    op.create_table('gps_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_reports_train_no'), 'gps_reports', ['train_no'], unique=False)
    op.create_index('ix_gps_train_time', 'gps_reports', ['train_no', 'created_at'], unique=False)
    op.create_table('spotter_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_code'], ['station_master.station_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotter_reports_train_no'), 'spotter_reports', ['train_no'], unique=False)
    op.create_index('ix_spotter_train_time', 'spotter_reports', ['train_no', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spotter_train_time', table_name='spotter_reports')
    op.drop_index(op.f('ix_spotter_reports_train_no'), table_name='spotter_reports')
    op.drop_table('spotter_reports')
    op.drop_index('ix_gps_train_time', table_name='gps_reports')
    op.drop_index(op.f('ix_gps_reports_train_no'), table_name='gps_reports')
    op.drop_table('gps_reports')
    op.drop_table('train_positions')
    # ### end Alembic commands ###
